### ISSUE TITLE
impossible de faire fonctionner framadate

### ISSUE THREAD

**Issue by gilluc** [BastienF/framadate-in-docker#1]
bonjour bastien,

comme le port 3306 est déjà pris, j'ai déplacé 'mysql' sur le port 3506.
et là, que ce soit par l'interface ou par le fichier config.php, j'ai systématiquement une erreur de connection à la base de données.

par le config.php c'est un plantage PDO:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/app/classes/Framadate/FramaDB.php:30 Stack trace: #0 /var/www/html/app/classes/Framadate/FramaDB.php(30): PDO->__construct('mysql:host=mysq...', 'root', 'rootpassword') #1 /var/www/html/app/inc/init.php(43): Framadate\FramaDB->__construct('mysql:host=mysq...', 'root', 'rootpassword') #2 /var/www/html/index.php(23): include_once('/var/www/html/a...') #3 {main} thrown in /var/www/html/app/classes/Framadate/FramaDB.php on line 30

![Image](https://github.com/user-attachments/assets/83e4cb59-6a7d-4299-b142-9211135ed755)

![Image](https://github.com/user-attachments/assets/7e715012-1c34-45bb-b5fe-590899bea6a7)

**Comment by gilluc** [comment]
**enfin un docker compose qui a marché (ça vaut cher du coup!!!)**

```
version: '3'

services:
  framadate:
    image: bastienf/framadate
    container_name: framadate
    restart: always
    ports:
      - "6080:80"
    environment:
      - FRAMADATE_DB_HOST=db
      - FRAMADATE_DB_NAME=framadate
      - FRAMADATE_DB_USER=framadate
      - FRAMADATE_DB_PASSWORD=framadatepassword
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: framadatedb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: framadate
      MYSQL_USER: framadate
      MYSQL_PASSWORD: framadatepassword
    command: --sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  
```
